//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string StudentCode { get; set; }
        public string Stu_FirstName { get; set; }
        public string Stu_LastName { get; set; }
        public Nullable<System.DateTime> Stu_DOB { get; set; }
        public string Stu_Gender { get; set; }
        public string Stu_Email { get; set; }
        public string Stu_PhoneNumber { get; set; }
        public string Stu_Address { get; set; }
        public string Stu_Password { get; set; }
        public string Class_ID { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
