//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSchedule
    {
        public int TestSchedule_ID { get; set; }
        public string Subject_ID { get; set; }
        public System.DateTime Testing_Date { get; set; }
        public System.TimeSpan Begining_Time { get; set; }
        public string Testroom { get; set; }
        public Nullable<int> StuTest_Quantity { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
